name = "miniflux-ai"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-06"

[build]
command = "cargo install -q worker-build && worker-build --release"

[triggers]
crons = ["*/5 * * * *"]

[vars]
MINIFLUX_URL = "your miniflux url"
MINIFLUX_USERNAME = "your miniflux username"
MINIFLUX_PASSWORD = "your miniflux password"
MINIFLUX_WEBHOOK_SECRET = "your miniflux webhook secret"
OPENAI_URL = "https://api.cloudflare.com/client/v4/accounts/{your cloudflare account}/ai"
OPENAI_TOKEN = "your cloudflare workers AI token"
OPENAI_MODEL = "@cf/qwen/qwen1.5-14b-chat-awq"
WHITELIST_URL = "https://www.zaobao.com/news/china,https://t.me/s/theinitium_rss,https://cn.nytimes.com,https://www.latepost.com/news/get-news-data,https://t.me/s/wsj_rss,http://www.zhihu.com,https://new.qq.com/omn/author/5157372,https://www.huxiu.com"